services:
  ui:
    image: ui
    build:
      context: ./src/web/home
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: ui
    environment: 
      NEXT_TELEMETRY_DISABLED: "1"
      NODE_ENV: production
    expose:
      - "3000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ui.rule=Host(`home.marcel-sigl.dev`)"
      - "traefik.http.routers.ui.entrypoints=web"
      - "traefik.http.services.ui.loadbalancer.server.port=3000"
    networks: [ proxy ]
    
  gateway:
    image: gateway
    build:
      context: .
      dockerfile: src/gateway/Gateway/Dockerfile
    restart: unless-stopped
    container_name: gateway
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://0.0.0.0:8080
    expose:
      - "8080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gateway.rule=Host(`api.marcel-sigl.dev`)"
      - "traefik.http.routers.gateway.entrypoints=web"
      - "traefik.http.services.gateway.loadbalancer.server.port=8080"
    networks: [ proxy ]

networks:
  proxy:
    external: true